### ISSUE TITLE
Can we have API using extends?

### ISSUE THREAD

**Issue by gaearon** [brigand/smart-mixin#3]
I don't know how ES6 classes work very well but I wonder if we can have a syntax like `class MyComponent extends mixin(ReactComponent, SomeMixin, SomeOtherMixin)`? Or is it already possible?

**Comment by brigand** [comment]
It would be nice, but it's unfortunately not feasible.  The mixin function needs MyComponent.prototype as an argument so that if you define e.g. componentDidMount on both, it can merge the two functions together.  Otherwise you'd have to define the component's componentDidMount (and every other function with the MERGE strategy) with a super call if defined.

``` js
componentDidMount(){
  super.componentDidMount && super.componentDidMount();
  // put actual code here
}
```

It'd also make mixin time errors unable to consider the component class, so defining a function in the component class and a mixin would result in silently shadowing it.

**Comment by gaearon** [comment]
We chatted with somebody else who tried to implement mixins and here's proof of concept he had: http://jsbin.com/jirulimito/1/edit?js,console

Can you please explain why it is flawed, if it is?

I'm still finding it hard to grasp all of this..

**Comment by brigand** [comment]
So ignoring the error part (which I think is important, and it'd be a step down from react's mixins without it), it's close, but less convenient after the first line.

You have to call super, but you do have to guard it like in my snippet above.  Otherwise if no mixin implements componentWillMount, you're calling undefined (TypeError).  This means that `class A extends mixin(Component, {})` would error on componentWillMount, but it should be a noop.

The ordering appears to be the same as react, which isn't the case in react-mixin, but I don't have any ideas on how to fix that (other than having the user use mixins in the reverse order).  The order in react and that jsbin is Mixin1, Mixin2, ..., MixinN, Component.

I'd rather define the mixins to include under the class, than an extra line in every mergeable method, less helpful errors and shadowing allowed.

---

It's a POC, but if the implementation is finished:

React.Component.prototype.componentWillMount isn't defined, and I don't see why it'd be expected, so this throws an error if you remove it (setState and currently, forceUpdate are provided by R.C.p).  It was also missing a guard on originalComponentWillMount.call.

Here's an updated version with some fixes: http://jsbin.com/lipibeqedu/3/edit?js,console

**Comment by gaearon** [comment]
Thanks for the explanation!
